spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: root
    driver-class-name: org.h2.Driver

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect

  data:
    rest:
      basePath: /api

server:
  ssl:
    key-store: classpath:identity.jks
    key-store-password: secret
    key-store-type: PKCS12

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000

material:
  upload-dir: /home/maksfox/tmp/project

homework:
  upload-dir: /home/maksfox/tmp/project
